---
# defaults file for sa-kong

role_dir: "{{role_path}}"
kong_version: "1.0.0"

kong_nginx_template: default_nginx.template

kong_admin_http: "0.0.0.0:8001"
kong_admin_https: "0.0.0.0:8444"
kong_proxy_http: "0.0.0.0:8000"
kong_proxy_https: "0.0.0.0:8443"

kong_default_properties:
  - {regexp: "^#?proxy_listen  *", line: "proxy_listen = {{kong_proxy_http}}"}
  - {regexp: "^#?proxy_listen_ssl  *", line: "proxy_listen_ssl = {{kong_proxy_https}}"}
  - {regexp: "^#?admin_listen  *", line: "admin_listen = {{kong_admin_http}}"}
  - {regexp: "^#?admin_listen_ssl  *", line: "admin_listen_ssl = {{kong_admin_https}}"}
  - {regexp: "^#?database  *", line: "database = {{kong_db}}"}
  - {regexp: "^#?pg_host  *", line: "pg_host = {{kong_pg_host}}"}
  - {regexp: "^#?pg_port  *", line: "pg_port = {{kong_pg_port}}"}
  - {regexp: "^#?pg_user  *", line: "pg_user = {{kong_pg_user}}"}
  - {regexp: "^#?pg_password  *", line: "pg_password = {{kong_pg_password}}"}
  - {regexp: "^#?pg_database  *", line: "pg_database = {{kong_pg_database}}"}
  - {regexp: "^#?pg_ssl  *", line: "pg_ssl = {{kong_pg_ssl}}"}
  - {regexp: "^#?pg_ssl_verify  *", line: "pg_ssl_verify = {{kong_pg_ssl_verify}}"}

kong_properties: []

kong_db: postgres
kong_pg_host: "127.0.0.1"
kong_pg_port: 5432
kong_pg_user: kong
kong_pg_password: kong
kong_pg_database: kong
kong_pg_ssl: off
kong_pg_ssl_verify: off

# https://konghq.com/plugins/
kong_plugins:
    - acl
    - basic-auth
    - cors
    - file-log
    - hmac-auth
    - http-log
    - ip-restriction
    - jwt
    - key-auth
    - galileo
    - oauth2
    - rate-limiting
    - response-ratelimiting
    - response-transformer
    - request-size-limiting
    - request-transformer
    - ssl
    - tcp-log
    - udp-log

kong_dist_url_debian: "https://bintray.com/kong/kong-community-edition-deb/download_file?file_path=dists/kong-community-edition-{{ kong_version }}.{{ ansible_distribution_release }}.all.deb"
kong_dist_url_centos: "https://dl.bintray.com/kong/kong-community-edition-rpm/rhel/7/kong-community-edition-{{ kong_version }}.rhel7.noarch.rpm"
kong_dist_url_rhel7: "https://dl.bintray.com/kong/kong-community-edition-rpm/rhel/7/kong-community-edition-{{ kong_version }}.rhel7.noarch.rpm"